### ISSUE TITLE
Installed non-Remastered Starcraft won't appear in Galaxy unless launched

### ISSUE THREAD

**Issue by EustaceCS** [FriendsOfGalaxy/galaxy-integration-battlenet#10]
Never launched this game before.
Had to launch after install, otherwise Galaxy was unable to locate it.
Using v0.38 plugin. Win10 .

**Comment by FriendsOfGalaxy** [comment]
so - you do not see SC in you library at all in the first place? can you drop some logs here?

**Comment by FriendsOfGalaxy** [comment]
Battle.net API returns games played games only as owned (at least for trial or free versions). It is not enough to install it. We're returning it as local game to Galaxy but they are display only games that you owned - not only installed. So no game will be displayed.

Workaround is possible but it much work and I'm not sure if worth to do (this plugin has already many workarounds).

**Comment by FriendsOfGalaxy** [comment]
Hi, if the issue still persist please report here: https://github.com/bartok765/galaxy_blizzard_plugin
This repo is not maintained anymore
