### ISSUE TITLE
Request for CN region Battle.net account login

### ISSUE THREAD

**Issue by zestybaby** [FriendsOfGalaxy/galaxy-integration-battlenet#11]
Account login is currently limited to other regions except for CN region which isn't linked like the others.

**Comment by FriendsOfGalaxy** [comment]
True. Pull request from China user is welcomed, as we have limited possibility to code and test this feature

**Comment by FriendsOfGalaxy** [comment]
As far as I know, it is already done here https://github.com/bartok765/galaxy_blizzard_plugin

**Comment by zestybaby** [comment]
Good to know, thanks!
