### ISSUE TITLE
World of Warcraft Classic doesn't launch when clicking play

### ISSUE THREAD

**Issue by RejectedGalaxy** [FriendsOfGalaxy/galaxy-integration-battlenet#12]
If you click play on World of Warcraft Classic in the GOG Galaxy 2.0 launcher all that happens is it opens on the B.Net app, but does not launch the game.

**Comment by FriendsOfGalaxy** [comment]
Yea, we know - Battle net do not support that for WOW Classic, sorry.

**Comment by chazragg** [comment]
This is due to classic wow being a sub catagory of world of warcraft not it's own game on the launcher. it is on the same level as PTR and Beta installs sadly.

**Comment by FriendsOfGalaxy** [comment]
Yup, that's true. We hardcoded special workaround just to open Battle.net on WoW page with selected "WoW classic" type of the game.

![wowclassic](https://user-images.githubusercontent.com/48480506/68486534-8b372c00-0241-11ea-8fe7-752e4a5d89e6.png)

So it is pretty convenient, just one more click. There is no other option to run this game - exactly the same is happen when you double-click on executable.
