### ISSUE TITLE
Modern Warfare Beta Not Working

### ISSUE THREAD

**Issue by Curotos** [FriendsOfGalaxy/galaxy-integration-battlenet#13]
It popped up in my all games tab but when I click on it, it just says install at the top. When I click on it, it says its launching battle.net but nothing ever opens. It also does this for world of warcraft classic. I was just wondering if there was any solution for this?

**Comment by Scorpion9four** [comment]
I have the same issue.

**Comment by FriendsOfGalaxy** [comment]
Working on it, no ETA yet.
