### ISSUE TITLE
Games only saying "Install"

### ISSUE THREAD

**Issue by Curotos** [FriendsOfGalaxy/galaxy-integration-battlenet#18]
A few days ago suddenly all of my battle games would all say install instead of play. I open battle to see if it is because anything needed to be updated but this was not the case. I tried installing the most updated version of the integration but it still is not working, any help would be much appreciated!

**Comment by FriendsOfGalaxy** [comment]
Hey, can you provide your logs from the C:\ProgramData\GOG.com\Galaxy\logs directory?

**Comment by Curotos** [comment]
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3746358/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by Curotos** [comment]
Also sorry it took so long to get back!

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for logs. Looks like you battlenet database stopped reporting installed games (only overwatch is reported - can you see it as installed in Galaxy?). Or we can no longer parse it correctly. Can you send your database from
`%ALLUSERSPROFILE%\Battle.net\Agent\product.db` ?

**Comment by Curotos** [comment]
Overwatch was not showing in the installed tab and I found the database file but when I try to drag it into this chat box, it says the file is hidden try again with another file?

**Comment by FriendsOfGalaxy** [comment]
pack it as .zip archive, github for some reason accepts only some file types. Note that we need `C:\ProgramData\Battle.net\Agent\product.db`, not `C:\ProgramData\Battle.net\Agent\.product.db` (with a leading dot)

**Comment by FriendsOfGalaxy** [comment]
Hi, if the issue still persist, please report here: https://github.com/bartok765/galaxy_blizzard_plugin
This repo is not maintained anymore
