### ISSUE TITLE
Games not owned/not available on Battle.net anymore shows up in GOG Galaxy library

### ISSUE THREAD

**Issue by ElAlderson** [FriendsOfGalaxy/galaxy-integration-battlenet#19]
Destiny 2 still shows up under Battle.net in spite of it being moved to Steam. My library shows Destiny 2 from both Battle.net and Steam accounts currently. Also, I had played Overwatch during some "free to play for a week" promotions but I don't own the game. Nevertheless, it shows up under Battle.net in GOG Galaxy.

**Comment by Gaboris** [comment]
I'm actually not sure how Galaxy2.0 handles "removed" games, but so far I haven't seen it do any "garbage collection" so it might just look for games to add or refresh, but it won't check to see if they still apply.

Can anyone confirm or deny that just so we know if it's really the code's fault?

**Comment by FriendsOfGalaxy** [comment]
Are you able to install game via Battle.net plugin?

**Comment by ElAlderson** [comment]
> 
> 
> Are you able to install game via Battle.net plugin?

Yes, no problems there. In fact I could install Overwatch which isn't possible from the Battle.net launcher although I couldn't play it upon launch as I do not own the game.

**Comment by FriendsOfGalaxy** [comment]
> Can anyone confirm or deny that just so we know if it's really the code's fault?

Yes, it's a thing to be done. Review blizzard api response it if really returns those removed titles as "owned" and if so - find possible workaround. PR welcomed

**Comment by FriendsOfGalaxy** [comment]
If the issue still persists - please report here: https://github.com/bartok765/galaxy_blizzard_plugin linking this issue
This repo is not maintained anymore.
