### ISSUE TITLE
Plugin crashes when attempting to connect

### ISSUE THREAD

**Issue by caveman250** [FriendsOfGalaxy/galaxy-integration-battlenet#2]
Upon hitting "Connect" i am greeted with the confirmation page that shows me what i will and wont be connecting eg: games/friends ect.

After hitting connect the integration sits on "Connecting..." for awhile before showing "Not responding" and then "Plugin has crashed. Retry."

If there is any information i can offer to help please let me know

**Comment by coreydwillis** [comment]
Similar issue. Every time I launch Gog Galaxy 2.0, Battle.net fails to connect, but once I retry it, it will work again.

**Comment by rauscheb** [comment]
The plugin is also crashing for me after selecting "Connect". It never prompts for login credentials. It fails to connect and gives only the options to "Retry" and "Disconnect"

**Comment by JRBourque** [comment]
Had the same issue here but was able to make it work by placing the unzipped folder in C:\Users\[Username]\AppData\Local\GOG.com\Galaxy\plugins\downloaded

I have a Readme improvement locally but i don't have the right to push to the repo for a PR

**Comment by caveman250** [comment]
Ahh yep, having the unzipped folder in *both* downloaded and installed did it for me

This should really be in the readme

**Comment by FriendsOfGalaxy** [comment]
The latest version has a fix for storing cookies. Please check if it works for you:
https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/releases/tag/v0.37

Replacing old files in 
`%localappdata%\GOG.com\Galaxy\plugins\installed`
should be enough to get it work.

I would also delete anything related to battle.net in the 
 `%localappdata%\GOG.com\Galaxy\plugins\downloaded` folder, just to be sure.

Remember to disconnect it first to get rid of old credentials.
