### ISSUE TITLE
B.net attempts to relaunch every time I try to start a game

### ISSUE THREAD

**Issue by moeraccoon** [FriendsOfGalaxy/galaxy-integration-battlenet#20]
When I try to start a game from galaxy battlenet relaunch itself and asks me to login rather than using the already existing stance of battlenet.

I have the options setup on my bnet to let me start multiple stances of it and it asks me for password every time so that's the only thing that I guess could cause the issue.

**Comment by ElAlderson** [comment]
Correct guess ! If you "Allow multiple instances of Battle.net", then "It'll almost certainly cause weird things to happen". Well, the setting itself seems to be the problem, disable it and Battle.net logs in automatically with no issues after relaunch.

**Comment by FriendsOfGalaxy** [comment]
@ElAlderson right.
I do not know any pleasant solution for this, closing for now
