### ISSUE TITLE
Modern Warfare doesn't show up properly

### ISSUE THREAD

**Issue by baconjets** [FriendsOfGalaxy/galaxy-integration-battlenet#21]
Galaxy thinks that the MW beta is the actual game, and the actual game won't appear.

**Comment by TheRealNox** [comment]
I was about to create a ticket :)
I'm trying to find in my battle net account and launcher anyway to get rid of the beta but it does not appear anywhere :/

**Comment by piergud** [comment]
#22 Opened a pull request for it 😃

**Comment by FriendsOfGalaxy** [comment]
Fixed. Let me know if there is still an issue
