### ISSUE TITLE
Developer Signature Required on macOS build

### ISSUE THREAD

**Issue by jamesstidard** [FriendsOfGalaxy/galaxy-integration-battlenet#24]
Hi,

Just a heads up, I just tried to install this plugin on macOS 10.15 which requires executables to be signed with a developer certificate. I assume the way round this is to build the package from source for the moment.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1797906/69006837-fb723b80-092c-11ea-83fb-682260ddf9ff.png">

Thanks for the plugin.

**Comment by jamesstidard** [comment]
I gave a shot at building this but I get the message `Can't find any collection named 'tasks'!`. Maybe the project no longer uses `invoke` or there's a uncommitted file.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for rising this up.

I cannot check how it works right now, but you can try to follow macos support instructions from https://support.apple.com/en-us/HT202491:
>In macOS Catalina and macOS Mojave, when an app fails to install because it hasn’t been notarized or is from an unidentified developer, it will appear in System Preferences > Security & Privacy, under the General tab. Click Open Anyway to confirm your intent to open or install the app.
/img/
>The warning prompt reappears, and you can click Open.*
/img/
>The app is now saved as an exception to your security settings, and you can open it in the future by double-clicking it, just as you can any authorized app.

Sadly you will have to do this probably for many files.

Building from source - right, tasks.py file is missed. I'll commit this soon

**Comment by jamesstidard** [comment]
@FriendsOfGalaxy, The update to the client now lets you search and install via the client. This seems to have got around the notarisation issue 🍾

**Comment by JaseHadd** [comment]
@FriendsOfGalaxy sorry to comment on a closed issue, but I'm still having the issue here and would really like to be able to build & notarize myself, but I'm missing the `tasks.py` file. Any chance you could commit it to master or share it here?

**Comment by bartok765** [comment]
@jasef for now I've added tasks.py in here (works only with my repo): https://github.com/bartok765/galaxy_blizzard_plugin
