### ISSUE TITLE
Can't find this integration using built-in search

### ISSUE THREAD

**Issue by JanPokorny** [FriendsOfGalaxy/galaxy-integration-battlenet#25]
When I enter `Battle.net` or `*` into the built-in search in Galaxy, the Battle.net plugin does not appear unless installed manually. (I also reported this to the Galaxy Mantis tracker, but I am not sure if this is a Galaxy or this plugin issue.)

**Comment by JanPokorny** [comment]
This now appears to be fixed.

**Comment by FriendsOfGalaxy** [comment]
Note that Galaxy shows different repository: https://github.com/FriendsOfGalaxy/galaxy-integration-blizzard
It has similar content.

**Comment by JanPokorny** [comment]
@FriendsOfGalaxy That's a little bit confusing. Why did you decide to deprecate this repository and create a new one under a different name?

**Comment by FriendsOfGalaxy** [comment]
Well, I have no time to maintain this integration any more (see readme) so I've decided to give it to someone else and just host it via auto-sync fork as other community plugins (wargaming, bethesda, rockstar...). And that is fortunate that the second repository has different name - I cound't fork repository that has the same name. 

To sum up all traffic should be slowly passed to https://github.com/bartok765/galaxy_blizzard_plugin
and FriendsOfGalaxy will only host this repo for better convertibility.

**Comment by JanPokorny** [comment]
@FriendsOfGalaxy Understood. I have created a PR to awesome-gog-galaxy to add this change (https://github.com/Mixaill/awesome-gog-galaxy/pull/66).

Note that GitHub has a feature where you can mark the whole repository as deprecated -- adds a yellow stripe to the top of the page. You might want to use that, the notice in README is easy to miss (eg. if you don't scroll that far down and go to issues directly, or if you are linked directly to the issues page).

Also you can add the deprecation notice to the repo description (that is shown right under the repo name).

**Comment by FriendsOfGalaxy** [comment]
Thanks, I've changed also description. I see that "archive" github feature disables commenting - let us give some time for open issues and use it later.
