### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by Frequel** [FriendsOfGalaxy/galaxy-integration-battlenet#26]
i am trying to connect my battle.net account with google authentication and it crash every time

**Comment by FriendsOfGalaxy** [comment]
Can you attach battlenet logs? They are in: 
`%programdata%\GOG.com\Galaxy\logs` commonly `C:\ProgramData\GOG.com\Galaxy\logs`

**Comment by Frequel** [comment]
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3902005/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by FriendsOfGalaxy** [comment]
ok, I see you've tried many times. But absolutely no sign of crash or any error.

Could you please attach also `GalaxyClient.log` just after trying to connect battle.net?

**Comment by Frequel** [comment]
[GalaxyClient.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3935005/GalaxyClient.log)
[GalaxyClientService.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3935006/GalaxyClientService.log)

**Comment by FriendsOfGalaxy** [comment]
Thanks, I still do not see things related to battle.net plugin. Have you try to launch it just before attaching logs as I asked for?

**Comment by MonkeyDMax92** [comment]
I also crash the plugin when everything is well linked. I received an SMS from Battlenet "For security reasons, your account is locked" due to the multiple reconnections without doubts.
[GalaxyClient.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3996436/GalaxyClient.log)

**Comment by FriendsOfGalaxy** [comment]
`2019-12-23 22:39:18.486 [Error][ (0)] [TID 126844][galaxy_client]: Plugin - pluginID/battlenet_ba170431-0649-482f-863b-d248592f1842 is not responding.`

Plugin apparently is stuck on something.

@MonkeyDMax92 can you upload also plugin log just after a crash?

**Comment by MonkeyDMax92** [comment]
The plugin no longer seems to crash, it has probably stabilized by itself. However, each time you start GOG Galaxy, some plugins are disconnected. The Rockstar and Battlenet plugins require me to login again.
