### ISSUE TITLE
Game time is not recorder

### ISSUE THREAD

**Issue by tyrirn** [FriendsOfGalaxy/galaxy-integration-battlenet#27]
I've added this integration, played one of my Bnet games (D3) for 2H, but the time was not recorded.

**Comment by tyrirn** [comment]
Maybe we can get the played time from Bnet in the future?

**Comment by FriendsOfGalaxy** [comment]
Last time I've checked, battlenet do not track game times for it's games (at least there is no public API for this). So we cannot either.

**Comment by tyrirn** [comment]
I see, but before i knew about this integration, I had the Bnet games as 'Other' and that time was counted, can't we at least get that kind of local counting?

**Comment by FriendsOfGalaxy** [comment]
That was tracking done by galaxy, which it doesn't do if you are using an integration. 

Its up to GOG how they handle this. Feel free to report on their side

**Comment by FriendsOfGalaxy** [comment]
yes, this is a feature request for Galaxy and Galaxy API. To track gametime they need to design a flow to ask plugin for executable names. Feel free to raise this issue on Galaxy side. I also think this will be useful.
