### ISSUE TITLE
Games not showing up

### ISSUE THREAD

**Issue by Nerdball2012** [FriendsOfGalaxy/galaxy-integration-battlenet#28]
I have connected my battlenet account, but none of my games appear to be populating. Checking the logs in gog/galaxy, it says its finding games and adding them, but none are available on the lists (with the exception of the WoW-classic I manually added)
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3902725/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by FriendsOfGalaxy** [comment]
Looks that plugin sends data correctly. Probably. Please report an issue to Galaxy by cogwheel menu. 

To workaround your problem you can try to
- exit galaxy
- remove storage (files from: `%ProgramData%\GOG.com\Galaxy\storage\` +  `%ProgramData%\GOG.com\Galaxy\storage\plugins\battlenet_ba170431-0649-482f-863b-d248592f1842-50161341869753009-storage.db`
- launch, reconnect plugin

Let me know it works for you

**Comment by UnhealthyKraken** [comment]
I am having the same issues, I have installed and removed the plugin multiple times, the logs show that it is detecting the games, and their install location, they are just not being added.

I have removed the storage files like you suggested above but to no avail

**Comment by AOClaus** [comment]
Same issue. Got an email from Blizzard telling me that permissions were granted, but games aren't showing up.

**Comment by AOClaus** [comment]
I've noticed that Battlenet isn't showing up as a platform in the lister of filters for me, it's just showing up as a favorite.

**Comment by FriendsOfGalaxy** [comment]
@Nerdball2012 I've missed this info from OP but looks like one of your account is marked as locked. See #31 . 

Try now - a new release with that fix was already deployed
