### ISSUE TITLE
Battle.net not detected (Play opens Battle.net website)

### ISSUE THREAD

**Issue by pannal** [FriendsOfGalaxy/galaxy-integration-battlenet#29]
**Describe the bug**
When I click "play" on Call of Duty: Modern Warfare, this website opens instead of the game: https://www.blizzard.com/en-us/apps/battle.net/desktop

**Expected behavior**
Call of Duty: Modern Warfare should launch.

**Attached logs**
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3933164/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by pannal** [comment]
Might be a duplicate of #8, currently trying to figure out what's up.

**Comment by pannal** [comment]
OK, this was fixed by removing the Battle.net installation folder and the one inside the all users profile folder. After reinstalling Battle.net it gets opened when clicking Play on CoD.

It's expected behaviour that the game itself doesn't open, just the launcher, yes?

Edit: It does, but only if the Battle.net launcher is already active. Otherwise it just opens it and not the game.

**Comment by FriendsOfGalaxy** [comment]
Hey,

looks like battle.net client weren't found in registry. That strange. If anyone has similar issue, please run `regedit` program and find `HKEY_CLASSES_ROOT\battlenet\shell\open\command`. Then check if what executable path it contains (before you reinstall battle.net).

>It's expected behaviour that the game itself doesn't open, just the launcher, yes?

After clicking Play in Galaxy, battlenet is poped-up with pressed Play, game starts and then a launcher is hidden. 

But in case of game update or in some cases when game is during download (but already playable) this may result in some lag and game is not launched

**Comment by dandepeched** [comment]
> looks like battle.net client weren't found in registry. That strange. If anyone has similar issue, please run `regedit` program and find `HKEY_CLASSES_ROOT\battlenet\shell\open\command`. Then check if what executable path it contains (before you reinstall battle.net).

I have the same issue. 'battlenet' entry is not present in HKEY_CLASSES_ROOT.
Should I investigate anything else before re-installing client?

**Comment by FriendsOfGalaxy** [comment]
And what about 
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Battle.net` ?
If not, is there Battle.net listed in control panel - uninstall section?

**Comment by dandepeched** [comment]
It is absent everywhere...
I installed Battle.Net on secondary disc, so maybe installation records got corrupted during some of major Windows updates or rollback that I did from the last one.
Thanks for your help, will re-install it then.
