### ISSUE TITLE
Diablo II & III not detected as installed.

### ISSUE THREAD

**Issue by Mobeeuz** [FriendsOfGalaxy/galaxy-integration-battlenet#3]
Here is the registry entry for D2:

﻿[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Diablo II]
"DisplayIcon"="D:\\Program Files (x86)\\Diablo II\\Diablo II.exe"
"DisplayName"="Diablo II"
"UninstallString"="C:\\Program Files (x86)\\Common Files\\Blizzard Entertainment\\Diablo II\\Uninstall.exe"
"Publisher"="Blizzard Entertainment"

and the registry entry for D3.

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Diablo III]
"DisplayName"="Diablo III"
"UninstallString"="\"C:\\ProgramData\\Battle.net\\Agent\\Blizzard Uninstaller.exe\" --lang=enUS --uid=diablo3_enus --displayname=\"Diablo III\""
"Comments"="Diablo III"
"Publisher"="Blizzard Entertainment"
"DisplayIcon"="D:\\Program Files (x86)\\Diablo III\\Diablo III.exe"
"InstallLocation"="D:\\Program Files (x86)\\Diablo III"
"InstallSource"="D:\\Program Files (x86)\\Diablo III"
"Contact"="Blizzard Support"
"HelpLink"="http://us.blizzard.com/support/"
"URLInfoAbout"="http://us.blizzard.com/support/"
"URLUpdateInfo"="http://us.blizzard.com/support/"

**Comment by FriendsOfGalaxy** [comment]
Hey,
thanks for the report, i can't reproduce this on my side. Can You provide your battlenet plugin logs found in C:\ProgramData\GOG.com\Galaxy\logs ?

You can provide them here or send as an email to friendsofgalaxy@gmail.com

**Comment by felipeparaujo** [comment]
@FriendsOfGalaxy This is probably related to the issues I was having and fixed in https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/pull/1 . Although, as Diablo II isn't a Battle.net launcher game, it won't get detected by the plugin.

**Comment by FriendsOfGalaxy** [comment]
@felipeparaujo latest commits introduce handling of classic blizzard games (like diablo II)

**Comment by Mobeeuz** [comment]
Sent

**Comment by FriendsOfGalaxy** [comment]
Diablo III detection should be fixed by #1 
Diablo II detection should be fixed on latest release as well.
Please check if it works for you.

**Comment by Mobeeuz** [comment]
It does indeed. Both are working as expected, thanks for the updates...
