### ISSUE TITLE
ModuleNotFoundError: No module named 'bnet'

### ISSUE THREAD

**Issue by elkangaroo** [FriendsOfGalaxy/galaxy-integration-battlenet#30]
I was looking into the development of this plugin but I am stuck with said error after installing dependencies. The module "bnet" is not listed in the requirements/*.txt files and the one found at https://pypi.org/project/bnet/ is a different one.
So my question is, where do you get the "bnet" module used in this plugin?

**Comment by FriendsOfGalaxy** [comment]
Hi, apparently I've forgot to add to src in CI. You can use bnet project you've found - plugin uses it but not latest release. I'll merge it in spare time.

**Comment by elkangaroo** [comment]
Thx, but unfortunately this is not the correct module. I tried bnet==0.2 and bnet==0.1, but they don't contain any of those:
`from bnet import connection_service_pb2, rpc_pb2, friends_service_pb2, authentication_service_pb2, presence_service_pb2`

**Comment by bartok765** [comment]
I have similar issue and for now I've just copied and edit this repo to be fully functional without the lacking module: https://github.com/bartok765/galaxy_blizzard_plugin

I've also added `tasks.py` to build the package and install locally.

**Comment by bartok765** [comment]
And apparently bnet module no longer works #32

**Comment by FriendsOfGalaxy** [comment]
@elkangaroo I'm sorry for misleading, bnet module was build here based on https://github.com/HearthSim/hsproto

You can get the code from from releases page of this package as is. But as it was mention, it currenly do not work. Unfortunately I won't have time to fix it any soon.

@bartok765 thanks for help and task.py.

**Comment by bartok765** [comment]
I've added bnet module from this repo releases to my repo.https://github.com/bartok765/galaxy_blizzard_plugin
I'm not experienced with google protobufs so any PR for firends recommendations / user presence is welcomed
