### ISSUE TITLE
Can't import friends from BNet

### ISSUE THREAD

**Issue by KozzyDV** [FriendsOfGalaxy/galaxy-integration-battlenet#32]
![BattleNet](https://user-images.githubusercontent.com/51876748/70871659-60cf5000-1ff1-11ea-859c-e14ae5373007.JPG)

I don't think this is currently supported but it would be nice to be able to import my friends list from BNet aswell. Can we also integrate chat??

**Comment by bartok765** [comment]
I've tested this in few scenarios and looks like plugin always sends empty list as recommended friends.

**Comment by KozzyDV** [comment]
So is that a problem with battle net not providing that data or the interface implementation isn’t quite right and could be fixed? ☺️

**Comment by FriendsOfGalaxy** [comment]
This repo is not maintained anymore. Closing. For further requests use this: Closing because repo is not mainta https://github.com/bartok765/galaxy_blizzard_plugin
