### ISSUE TITLE
Warcraft 3 standard doesn't appear, Frozen throne yes though.

### ISSUE THREAD

**Issue by BanCrash** [FriendsOfGalaxy/galaxy-integration-battlenet#33]
Hello! I have both Warcraft 3 Reign of Chaos and The Frozen Throne buyed as classical games, and both appears on my Blizzard account, but on gog galaxy only The Frozen Throne is detected. 

Shouldn't both games be detected instead only The Frozen Throne?

I don't know If I have to put some more information, Here I let the log.
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/4007147/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by BanCrash** [comment]
I didn't clarify well, both games are uninstalled, and The Frozen Throne is detected as such, but Reign of Chaos is not.

**Comment by FriendsOfGalaxy** [comment]
Hi @BanCrash 
I don't remember exactly but is it possible to play Standaard W3 if Frozen throne license is owned? How it looks like in BattleNet?

You've closed - does it mean it is fixed already?

**Comment by BanCrash** [comment]
Hello @FriendsOfGalaxy .

I don't have them installed right now, but when I did, I remember I can open both games without any issues. They don't appear on battleNet though, they only can be installed downloading the installators in the web.

![image](https://user-images.githubusercontent.com/11770760/72162595-8a964f80-33c2-11ea-827a-d58a51186d22.png)

"Descargar cliente de juego" means "Download game client".

About closing it, I close it because I thought this was abandoned. the issue still happens.

**Comment by FriendsOfGalaxy** [comment]
@BanCrash  Can you please send us or paste here your content of https://account.blizzard.com/api/classic-games website? (Please delete any sensitive data before doing so)

**Comment by BanCrash** [comment]
Hello @FriendsOfGalaxy , here I let the info:

{"classicGames":[{"localizedGameName":"Warcraft® III: Reign of Chaos®","regionalGameFranchiseIconFilename":"warcraft-iii.svg","cdKeys":["XXXXXXXXXXXXXXXXX"],"displayOrder":9001},{"localizedGameName":"Warcraft® III: The Frozen Throne®","regionalGameFranchiseIconFilename":"warcraft-iii.svg","cdKeys":["XXXXXXXXXXXXXXXX"],"displayOrder":9002}]}

**Comment by BanCrash** [comment]
This issue is now fixed on the new repository (https://github.com/bartok765/galaxy_blizzard_plugin)
