### ISSUE TITLE
Multiple WOW licenses in the same battlenet account

### ISSUE THREAD

**Issue by javierhimura** [FriendsOfGalaxy/galaxy-integration-battlenet#34]
In WOW you can have multiple subscriptions at the same time in the same BattleNet account that allows players to connect to the servers with multiple characters at the same time.

Currently, with GOG Launcher, there is no way to switch between those WOW secondary accounts when launching the game it always uses the last WOW account selected in the official BattleNet launcher.

PD: I do not mean having multiple BattleNet accounts. In BattleNet any player can own up to 8 licenses of WOW in the same BattleNet account

**Comment by FriendsOfGalaxy** [comment]
Hey, thanks for report. So how do you play those additional accounts? Is there any switcher in BattleNet? Screenshot would be lovely as I do not own multiple licenses.

**Comment by FriendsOfGalaxy** [comment]
![image](https://user-images.githubusercontent.com/48480506/72162768-db0dad00-33c2-11ea-8610-75f3bb412fe6.png)

i think this is it.

**Comment by javierhimura** [comment]
Yes, is that. There is a drop-down to select the WOW account when you have more than one, both in Retail WOW and Classic WOW

![imagen](https://user-images.githubusercontent.com/21158487/72166499-a4876080-33c9-11ea-961e-241fb88235e8.png)

![imagen](https://user-images.githubusercontent.com/21158487/72166471-96d1db00-33c9-11ea-8785-535c941d96b2.png)

**Comment by FriendsOfGalaxy** [comment]
Hi, please move this issue here: https://github.com/bartok765/galaxy_blizzard_plugin
This repo is not maintained anymore
