### ISSUE TITLE
World of Warcraft Play Time

### ISSUE THREAD

**Issue by Kezzic** [FriendsOfGalaxy/galaxy-integration-battlenet#36]
I am using the Galaxy's Community Integration for Battle.net, and WoW Classic and Retail WoW both open the launcher when I click play-- This is fine. But I noticed that neither track play time when I am done playing.

Which executable do I need to be linking to properly record game time played for both of these titles?

**Comment by FriendsOfGalaxy** [comment]
Hey. This integration does not support time tracking. And it is not possible to point to exe of a game that is coming from integration. Only manually adding games has Galaxy supported game tracking. So either linking WoW manually or use this plugin.

You can send issue on Galaxy mantis to add Galaxy native time tracking for plugin games if a plugin does not support this.

**Comment by Kezzic** [comment]
Oh, gotcha thanks. Is this plugin a separate thing from the integration? I thought this was the Github for the integration.

**Comment by FriendsOfGalaxy** [comment]
this plugin == this integration, just an other word.
