### ISSUE TITLE
Warcraft 3 showing incorrectly

### ISSUE THREAD

**Issue by robertkoch13** [FriendsOfGalaxy/galaxy-integration-battlenet#37]
Hi

I added the latest version of the Battle.net plugin, signed in, and it shows most of the games correctly - Starcraft Remastered, Starcraft 2, Diablo 2 and 3 and runs them correctly.

I own Warcraft 3 Reforged and I am able to run it correctly from Battle.Net, but in Gog Galaxy it only shows the option to Install, and clicking it does nothing.  It also shows Warcraft 3 Frozen Throne with the option to Play, but that also does nothing (I own the original Warcraft 3 and Frozen Throne, but as far as I know they are not installed anymore, having been overwritten by Reforged).
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/4542300/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)
[product.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/4542305/product.zip)

**Comment by FriendsOfGalaxy** [comment]
Hi, please report here: https://github.com/bartok765/galaxy_blizzard_plugin
This repo is not maintained anymore
