### ISSUE TITLE
*Free Games if you install through GOG Galaxy

### ISSUE THREAD

**Issue by a-desaulniers** [FriendsOfGalaxy/galaxy-integration-battlenet#38]
I just linked up my Battle.net to play call of duty, then noticed that every blizzard game was just available... So I downloaded OW and uhhhhhhh, it just worked. Thanks for giving me Free OW ig.....

**Comment by FriendsOfGalaxy** [comment]
Please report the issue here: https://github.com/bartok765/galaxy_blizzard_plugin. This repository is no longer used.
