### ISSUE TITLE
WoW and WoW Classic not showing up as separate games

### ISSUE THREAD

**Issue by majorffalcon** [FriendsOfGalaxy/galaxy-integration-battlenet#4]
They're separate .exes in different install folders so you would imagine they'd show up separately.

**Comment by FriendsOfGalaxy** [comment]
In 0.37 we made some changes in order to display WOW and WOW Classic. 
Can you confirm if that works for you?

**Comment by majorffalcon** [comment]
Yep! just updated and they're showing separately, thanks! 

Oddly it seems hitting "Play" on WoW classic opens the Bnet client, where I then have to hit "Play" again to open the game (whereas when I was launching WoW from bnet integration on gog galaxy 2 before, all I had to do was hit "play" in GoG galaxy and the game would launch.

Thanks for the solution
