### ISSUE TITLE
Have to reconnect after a while

### ISSUE THREAD

**Issue by ghost** [FriendsOfGalaxy/galaxy-integration-battlenet#5]
Plugin is working fine on my main desktop but on my main laptop, it keeps disconnecting.

**Comment by Darkenend** [comment]
Keeps losing connection for me too.

**Comment by BuryTomorrow12** [comment]
Happens all the time. After 30 min - 1 hour, I have to manually reconnect and give my consent regarding permision on the Galaxy 2.0 popup.

**Comment by BuryTomorrow12** [comment]
Just a quick reminder that this is still hapening. If any log is needed, I can provide it.

**Comment by FriendsOfGalaxy** [comment]
The latest version has a fix for storing cookies. Please check if it resolves the problem.
https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/releases/tag/v0.37

**Comment by PastorGL** [comment]
Same here, and after several attempts to reconnect plugin goes completely offline (0.37 too). From the log:

`2019-08-26 23:23:54,493 - root - INFO - Handling request: id=16, method=pass_login_credentials, params={'cookies': '****', 'credentials': '****', 'step': ''}
2019-08-26 23:23:56,362 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "16", "error": {"code": 101, "message": "Network error"}}`

Blizzard's app authenticates just fine on same PC at the same time. And in browser too. So it all looks like a shadow ban on BNet server side. May be, by User Agent, or something.

**Comment by ghost** [comment]
Haven't tried on my laptop but on the desktop it works quite fine. The "install" has been replaced by "launch" for Overwatch even.

**Comment by FriendsOfGalaxy** [comment]
@PastorGL  looks like we think your are offline ("Network error"). It is translated from `requests` `ConnectionError` which is raised in few cases in this line and few next: https://github.com/psf/requests/blob/67a7b2e8336951d527e223429672354989384197/requests/adapters.py#L453
It is probably too broad for our needs, as Galaxy switches to offline mode. And it may be potentially raised on ClosedPoolError: https://github.com/urllib3/urllib3/issues/951
More investigation is needed.
In case if it repeats please, make another issue.

For the current issue - maybe you're right about BNet ban. I'm working on better error handling.

@BuryTomorrow12 Does 0.37 works for you? I no, please send us logs. Thanks!

**Comment by FriendsOfGalaxy** [comment]
Can you check against latest v0.38?

**Comment by PastorGL** [comment]
Checked 0.38. Auth seems working and plugin doesn't go offline anymore 👍

**Comment by Darkenend** [comment]
Seems to be working fine with 0.38 👍
