### ISSUE TITLE
0.37 BattleNet games not updating

### ISSUE THREAD

**Issue by Fraicheur** [FriendsOfGalaxy/galaxy-integration-battlenet#6]
When I download and connect to the BNet API with 0.37, no games are showing up.
Everything works fine when I switch back to 0.36.

**Comment by FriendsOfGalaxy** [comment]
Thanks for report!
Could you please send us your log files `plugin-battlenet-xxxxx`? If multiple, send all. Assuming you are on Windows, logs are available under:
`%programdata%\GOG.com\Galaxy\logs`

**Comment by FelixMoelder** [comment]
Hey guys,

I've the same issue on macOS.
There seems to be some issue in finding the the Battle.net.config as Battle.net is not installed.
But as for other launchers I would expect that this should not be a requirement.

[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/files/3549590/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log.zip)

**Comment by FriendsOfGalaxy** [comment]
@FelixMoelder @Fraicheur can you check if the issue persists when using version 0.38 (newest release)?

**Comment by FelixMoelder** [comment]
@FriendsOfGalaxy This fixed it for me. Thanks!

**Comment by Fraicheur** [comment]
Problem solved here too!
Thanks
