### ISSUE TITLE
Starcraft (original) shown as Starcraft Remastered

### ISSUE THREAD

**Issue by FelixMoelder** [FriendsOfGalaxy/galaxy-integration-battlenet#7]
In my library Starcraft shows up as Starcraft Remastered.
As I own the original game but not the remastered one this should be, if possible, differentiated.
When selecting "Install" the installer for the original version starts. So it's just the wrong entry in Galaxy.

**Comment by EustaceCS** [comment]
Same for me.

**Comment by FriendsOfGalaxy** [comment]
That's the issue with Battle.net - it's report SC as one ID, If it's remaster is't up to Bnet backends and if you have licence or not. In the end this game is both non and remaster but Galaxy can display only one.

**Comment by ElAlderson** [comment]
> 
> 
> That's the issue with Battle.net - it's report SC as one ID, If it's remaster is't up to Bnet backends and if you have licence or not. In the end this game is both non and remaster but Galaxy can display only one.

Searching for starcraft on Galaxy 2.0 does show StarCraft and Starcraft:Remastered separately. It should indeed be a backend issue on part of Blizzard.

**Comment by FriendsOfGalaxy** [comment]
@FelixMoelder 
>When selecting "Install" the installer for the original version starts. So it's just the wrong entry in Galaxy.

You mean probably this:
![sc](https://user-images.githubusercontent.com/48480506/68497325-95aef100-0254-11ea-8170-5fdccc6e369f.png)

So:

Blizzard API that we use says: "you have starcraft remastered" when:
- you have bought starcraft remastered
- you have not bought starcraft remastered but played in classic version that is available for everyone for free via their client. No difference.

Battle.net probably knows another endpoint for this, but we don't know.

There is one more case, Starcraft Antology - that will be returned from second endpoint for classic games. I'm not sure, but it will be returned probably when you reedem you original cdkey here:
https://account.blizzard.com/overview

Let us know that will happen when you do it and resync battle.net integration. We currently have no install location and registry key for this, so appreciate any help.

**Comment by FriendsOfGalaxy** [comment]
Hi, if the issue still persists, please report the issue here: https://github.com/bartok765/galaxy_blizzard_plugin linking all important information from this thred.
This repo is not maintained anymore.
